info:
    app:
        name: ${spring.application.name}
        description: Catalog Service to perform operations related to catalogs
        version: 1.0.0
server:
    port: 8082
    shutdown: graceful
spring:
    application:
        name: catalog-service
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
    jackson:
        deserialization:
            fail-on-unknown-properties: true
    lifecycle:
        timeout-per-shutdown-phase: 30s
    datasource:
        url: ${MYSQL_URL}
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,env
    endpoint:
        health:
            show-details: always
    info:
        env:
            enabled: true
eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}
        lease-renewal-interval-in-seconds: 30
        lease-expiration-duration-in-seconds: 90
    client:
        service-url:
            defaultZone: ${EUREKA_URL}
        register-with-eureka: true
        fetch-registry: true
