services:
  mongodb:
    container_name: mongodb
    image: mongo:8.3.8
    restart: on-failure
    tty: true
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: user_service
      GLIBC_TUNABLES: "glibc.pthread.rseq=1"
    volumes:
      - /home/vicky/Projects/ShopSense/data/mongodb:/data/db
    networks:
      - dev_network
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --eval 'db.adminCommand({ ping: 1 })' --username user --password user --authenticationDatabase admin || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: on-failure
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/vicky/Projects/ShopSense/data/mysql:/var/lib/mysql
    networks:
      - dev_network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -proot" ]
      interval: 5s
      timeout: 5s
      retries: 50
networks:
  dev_network:
    driver: bridge

