info:
    app:
        name: ${spring.application.name}
        description: Payment Service to perform operations related to payments
        version: 1.0.0
server:
    port: 8086
    shutdown: graceful
spring:
    application:
        name: payment-service
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
    jackson:
        deserialization:
            fail-on-unknown-properties: true
    lifecycle:
        timeout-per-shutdown-phase: 30s
    datasource:
        url: ${MYSQL_URL}/${PAYMENT_SERVICE_DATABASE}?createDatabaseIfNotExist=true
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,env,prometheus
    endpoint:
        health:
            show-details: always
    info:
        env:
            enabled: true
    tracing:
        sampling:
            probability: 1.0
    otlp:
        metrics:
            export:
                enabled: false
    opentelemetry:
        resource-attributes:
            service.name: ${spring.application.name}
        tracing:
            export:
                otlp:
                    endpoint: ${TEMPO_URL}
    prometheus:
        metrics:
            export:
                enabled: true
logging:
    file:
        name: ./deploy/logs/${spring.application.name}.log
    pattern:
        correlation: "[%X{traceId:-},%X{spanId:-}]"
    level:
        root: info
        com.shopsense: trace
eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}
        lease-renewal-interval-in-seconds: 30
        lease-expiration-duration-in-seconds: 90
    client:
        service-url:
            defaultZone: ${EUREKA_URL}
        register-with-eureka: true
        fetch-registry: true
razorpay:
    key-id: ${RAZORPAY_KEY_ID}
    key-secret: ${RAZORPAY_KEY_SECRET}
    webhook-secret: ${RAZORPAY_WEBHOOK_SECRET}
stripe:
    secret-key: ${STRIPE_SECRET_KEY}
    publishable-key: ${STRIPE_PUBLISHABLE_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET}