info:
  app:
    name: ${spring.application.name}
    description: Media Service to perform operations related to file uploads
    version: 1.0.0
server:
  port: 8084
spring:
  application:
    name: media-service
  jackson:
    deserialization:
      fail-on-unknown-properties: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
cloudinary:
  cloud-name: dk0thpo8v
  api-key: 134228977232232
  api-secret: NDobC_qf5EXne8mGPLknFLRIJyg
