info:
  app:
    name: ${spring.application.name}
    description: User Service to perform operations related to user
    version: 1.0.0
server:
  port: 8081
spring:
  application:
    name: user-service
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  mongodb:
    host: localhost
    port: 27017
    username: root
    password: root
    database: user_service
    authentication-database: admin
  data:
    mongodb:
      auto-index-creation: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
