info:
    app:
        name: ${spring.application.name}
        description: User Service to perform operations related to user
        version: 1.0.0
server:
    port: 8081
    shutdown: graceful
spring:
    application:
        name: user-service
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
    jackson:
        deserialization:
            fail-on-unknown-properties: true
    lifecycle:
        timeout-per-shutdown-phase: 30s
    mongodb:
        host: ${MONGODB_HOST}
        port: ${MONGODB_PORT}
        username: ${MONGODB_USERNAME}
        password: ${MONGODB_PASSWORD}
        database: ${USER_DATABASE}
        authentication-database: ${MONGODB_AUTHENTICATION_DATABASE}
    data:
        mongodb:
            auto-index-creation: true
management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,env,prometheus
    endpoint:
        health:
            show-details: always
    info:
        env:
            enabled: true
    tracing:
        sampling:
            probability: 1.0
    otlp:
        metrics:
            export:
                enabled: false
    opentelemetry:
        resource-attributes:
            service.name: ${spring.application.name}
        tracing:
            export:
                otlp:
                    endpoint: http://localhost:4318/v1/traces
    prometheus:
        metrics:
            export:
                enabled: true
logging:
    file:
        name: ./deploy/logs/${spring.application.name}.log
    pattern:
        correlation: "[%X{traceId:-},%X{spanId:-}]"
    level:
        root: info
        com.shopsense: trace
eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}
        lease-renewal-interval-in-seconds: 30
        lease-expiration-duration-in-seconds: 90
    client:
        service-url:
            defaultZone: ${EUREKA_URL}
        register-with-eureka: true
        fetch-registry: true
