info:
    app:
        name: ${spring.application.name}
        description: Order Service to perform operations related to orders
        version: 1.0.0
server:
    port: 8085
    shutdown: graceful
spring:
    application:
        name: order-service
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
    jackson:
        deserialization:
            fail-on-unknown-properties: true
    lifecycle:
        timeout-per-shutdown-phase: 30s
    datasource:
        url: ${ORDER_POSTGRES_URL}
        username: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            username: ${REDIS_USERNAME}
            password: ${REDIS_PASSWORD}
            database: ${REDIS_CART_INDEX}
    sql:
        init:
            mode: always
            schema-locations: classpath:db/schema.sql
management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,env
    endpoint:
        health:
            show-details: always
    info:
        env:
            enabled: true
eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}
        lease-renewal-interval-in-seconds: 30
        lease-expiration-duration-in-seconds: 90
    client:
        service-url:
            defaultZone: ${EUREKA_URL}
        register-with-eureka: true
        fetch-registry: true
order:
    cart-key-prefix: ${REDIS_CART_KEY_PREFIX}
    cart-ttl-days: ${REDIS_CART_TTL_DAYS}
    tax-rate: ${ORDER_TAX_RATE}
    shipping-rate: ${ORDER_SHIPPING_RATE}