info:
    app:
        name: ${spring.application.name}
        description: Inventory Service to perform operations related to inventory
        version: 1.0.0
server:
    port: 8083
    shutdown: graceful
spring:
    application:
        name: inventory-service
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
    jackson:
        deserialization:
            fail-on-unknown-properties: true
    lifecycle:
        timeout-per-shutdown-phase: 30s
    sql:
      init:
          mode: always
          schema-locations: classpath:db/schema.sql
    datasource:
        url: ${INVENTORY_POSTGRES_URL}
        username: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,env
    endpoint:
        health:
            show-details: always
    info:
        env:
            enabled: true
eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}
        lease-renewal-interval-in-seconds: 30
        lease-expiration-duration-in-seconds: 90
    client:
        service-url:
            defaultZone: ${EUREKA_URL}
        register-with-eureka: true
        fetch-registry: true
reservation:
    expiry: ${RESERVATION_DURATION_MINUTES}